name: Sync Composer Files from SBPP

on:
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '35 1 * * *' # Run once a day at 0135

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v4.2.2
      - name: Fetch data - composer.json
        uses: githubocto/flat@mr/node16
        with:
          http_url: https://raw.githubusercontent.com/sbpp/sourcebans-pp/refs/heads/php81/web/composer.json # The data to fetch
          downloaded_filename: composer.json # The http_url gets saved and renamed in our repository 
      - name: Fetch data - composer.lock
        uses: githubocto/flat@mr/node16
        with:
          http_url: https://raw.githubusercontent.com/sbpp/sourcebans-pp/refs/heads/php81/web/composer.lock # The data to fetch
          downloaded_filename: composer.lock # The http_url gets saved and renamed in our repository 
  



          