name: Sync Composer Files from SBPP and notify

on:
  workflow_dispatch: # Required even though this is currently empty
  schedule:
    - cron: '25 1 * * *' # Run once a day at 0135

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps: 
      # The first step is to check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v4.2.2

      # Fetch data - composer.json
      - name: Fetch data - composer.json
        uses: githubocto/flat@mr/node16
        with:
          http_url: https://raw.githubusercontent.com/sbpp/sourcebans-pp/refs/heads/php81/web/composer.json
          downloaded_filename: composer.json

      # Fetch data - composer.lock
      - name: Fetch data - composer.lock
        uses: githubocto/flat@mr/node16
        with:
          http_url: https://raw.githubusercontent.com/sbpp/sourcebans-pp/refs/heads/php81/web/composer.lock
          downloaded_filename: composer.lock

      # Check if there are changes and commit and push if there are
      - name: Commit and push changes if there are any
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m 'Fetch latest composer files'
            git push
          fi

      # Notify via GitHub issue
      - name: Notify via GitHub issue
        if: success() && steps.commit_and_push.outputs.changes == 'true'
        uses: actions/github-script@v7.0.1
        with:
          script: |
            const { createIssue } = require('@actions/github/lib/utils');
            const octokit = createIssue();
            await octokit.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New Composer Files Downloaded and Pushed',
              body: 'The latest composer.json and composer.lock files have been downloaded and pushed to the repository.',
            });